load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain")
load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("@prelude//toolchains:rust.bzl", "system_rust_toolchain")

platform(
    name = "uefi",
    constraint_values = [
        "prelude//cpu/constraints:x86_64",
        "prelude//os/constraints:none",
    ],
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"]
)

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)

system_rust_toolchain(
    name = "rust",
    visibility = ["PUBLIC"],
    rustc_target_triple = select({
        "prelude//os:none": "x86_64-unknown-uefi",
        "DEFAULT": None,
    }),
)

system_rust_toolchain(
    name = "rust_uefi",
    visibility = ["PUBLIC"],
    rustc_target_triple = "x86_64-unknown-uefi",
    rustc_binary_flags = [
        "-C",
        "panic=abort",
    ],
)

system_cxx_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
)

system_cxx_toolchain(
    name = "cxx_uefi",
    link_style = "static",
    linker = "toolchains/lld-link.sh",
    visibility = ["PUBLIC"],
)
