rust_binary(
    name = "mkrootfs",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/main.rs",
    crate = "mkrootfs",
    edition = "2024",
    visibility = ["PUBLIC"],
    deps = [
        "//lib/crabfs:crabfs_std",
    ],
)
